# Generated by Django 5.1.6 on 2025-10-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_qa', '0002_remove_ds_answers_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ds_views',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinical_qa.ds_answers'),
            preserve_default=False,
        ),
    ]
