# Generated by Django 5.1.6 on 2025-10-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_qa', '0003_ds_views_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ds_views',
            name='answer',
        ),
    ]
