# Generated by Django 5.1.6 on 2025-10-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_qa', '0004_remove_ds_views_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ds_answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='clinical_qa.ds_questions'),
        ),
    ]
